version: '3.8'

services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    platform: linux/x86_64
    ports:
      - ${MAVEN_PORT}:8081
      - ${DOCKER_PORT}:5000
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g -XX:MaxDirectMemorySize=3g -Djava.util.prefs.userRoot=/nexus-data/javaprefs